feat: Add device group hierarchy support
PaloAltoNetworks/pan-os-python pull request #268
Opened 2020-09-18 22:38 UTC by shinmog

2020-09-22 02:22 UTC, btorresgil requested changes

2020-09-22 02:22 UTC, btorresgil commented on panos/panorama.py
> +    def get_device_group_hierarchy(self):
The method's name implies getting a hierarchy, which to me implies a nested dict. But as you say in the docstring it's a flat dict where the value is the DG parent. Perhaps another name could better represent this expectation?

2020-09-22 02:22 UTC, btorresgil commented on panos/panorama.py
> +        return dev.syncjob(resp)
I don't think we should force an async operation to act synchronously. Perhaps a `sync=False` argument would be better to make this sync optional? Or let the developer call `syncjob()` themselves on the result of this method.

2021-01-14 17:01 UTC, shinmog commented
sigh, commit history is messed up, going to redo this

2021-01-14 17:01 UTC, closed without merging

2021-02-05 10:01 UTC, tom0010 commented
Hey @shinmog did you do another PR for this? I just ran into this issue, so it'd be great if it could be merged :)