add feat logsettings system and config
PaloAltoNetworks/pan-os-python pull request #340
Opened 2021-05-18 15:36 UTC by kevinhuy

## Description

Add new functionality log settings on system and config.
This is done by adding two new class (LogSettingsSystem and LogSettingsConfig) in device.py.

## Motivation and Context

adds a new functionality.

## How Has This Been Tested?

This has been tested on panorama and physical firewall 5220 on version 9.0.10 with python 3.8
below result from panorama.

          templates tmpl-common-test;
+          config {
+            shared {
+              log-settings {
+                email {
+                  email_profil {
+                    server {
+                      1.1.1.1 {
+                        display-name myname;
+                        gateway 1.1.1.1;
+                        from myname@name.com;
+                        to tomyname@myname.com;
+                      }
+                    }
+                  }
+                }
+                system {
+                  match-list {
+                    logsystemsystettings_test {
+                      filter "All Logs";
+                      send-email email_profile;
+                      send-snmptrap snmp-profile;
+                      send-syslog srv-profile;
+                      send-http http_profile;
+                    }
+                  }
+                }

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [ X ] I have updated the documentation accordingly.
- [ X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ X ] All new and existing tests passed.

2021-05-18 15:41 UTC, kevinhuy commented
hello :)

@shinmog @btorresgil can you make an review of this MR, feel free to comment .

Thanks

2021-05-18 17:56 UTC, btorresgil commented
Thanks for sending this! Will review and merge ASAP.

2021-06-08 16:55 UTC, shinmog requested changes
Few actions items

2021-06-08 16:55 UTC, shinmog commented on panos/device.py
> +
Add a note that this is PAN-OS 8.0+

2021-06-08 16:55 UTC, shinmog commented on panos/device.py
> +        send_http (string): Send http profile
These are all `vartype="member"`, so the docstring should label them as lists not strings.

2021-06-08 16:55 UTC, shinmog commented on panos/device.py
> +
Add a note saying this is PAN-OS 8.0+.

2021-06-08 16:55 UTC, shinmog commented on panos/device.py
> +        send_http (string): Send http profile
These are `vartype="member"` so should be lists not strings in the docstring.

2021-06-22 12:47 UTC, kevinhuy commented
@shinmog i have apply the recommandation in your comments , thanks for your help :)

2021-06-24 15:15 UTC, shinmog approved these changes
lgtm

2021-06-24 15:16 UTC, merged